local S = minetest.get_translator(minetest.get_current_modname())

function nssm:register_noneatcraftitems (name, descr)
    minetest.register_craftitem("nssm:"..name, {
        description = descr,
        image = name..".png",
    })
end

function nssm:register_eatcraftitems (name, descr, gnam)
    minetest.register_craftitem("nssm:"..name, {
        description = descr,
        image = name..".png",
        on_use = minetest.item_eat(gnam),
        groups = { meat=1, eatable=1 },
		_hunger_ng = {satiates = gnam},
    })
end

function nssm_register_recipe (ingredient, dish, tictac)
    minetest.register_craft({
        type = "cooking",
        output = "nssm:"..dish,
        recipe = "nssm:"..ingredient,
        cooktime = tictac,
    })
end

-- Materials

nssm:register_noneatcraftitems ('sky_feather',S('Sky Feather'))
nssm:register_noneatcraftitems ('snake_scute',S('Snake Scute'))
nssm:register_noneatcraftitems ('eyed_tentacle',S('Eyed Tentacle'))
nssm:register_noneatcraftitems ('ant_queen_abdomen',S("Ant Queen's Abdomen"))
nssm:register_noneatcraftitems ('masticone_skull_fragments',S('Masticone Skull Fragments'))
nssm:register_noneatcraftitems ('tentacle_curly',S('Kraken Tentacle'))
nssm:register_noneatcraftitems ('lava_titan_eye',S('Lava Titan Eye'))
nssm:register_noneatcraftitems ('duck_beak',S('Duck Beak'))
nssm:register_noneatcraftitems ('ice_tooth',S('Ice Tooth'))
nssm:register_noneatcraftitems ('little_ice_tooth',S('Little Ice Tooth'))
nssm:register_noneatcraftitems ('digested_sand',S("Digested Sand"))
nssm:register_noneatcraftitems ('black_ice_tooth',S('Black Ice Tooth'))
nssm:register_noneatcraftitems ('tarantula_chelicerae',S('Tarantula Fangs'))
nssm:register_noneatcraftitems ('crab_chela',S('Crab Claw'))
nssm:register_noneatcraftitems ('cursed_pumpkin_seed',S('Cursed Pumpkin Seed'))
nssm:register_noneatcraftitems ('mantis_claw',S('Mantis Claw'))
nssm:register_noneatcraftitems ('manticore_fur',S('Manticore Fur'))
nssm:register_noneatcraftitems ('ant_hard_skin',S('Ant Husk'))
nssm:register_noneatcraftitems ('bloco_skin',S('Bloco Hide'))
nssm:register_noneatcraftitems ('crab_carapace_fragment',S('Crab Shell Fragment'))
nssm:register_noneatcraftitems ('crocodile_skin',S('Crocodile Hide'))
nssm:register_noneatcraftitems ('manticore_spine',S('Manticore Spine'))
nssm:register_noneatcraftitems ('night_feather',S('Night Feather'))
nssm:register_noneatcraftitems ('sun_feather',S('Sun Feather'))
nssm:register_noneatcraftitems ('duck_feather',S('Duck Feather'))
nssm:register_noneatcraftitems ('black_duck_feather',S('Black Duck Feather'))
nssm:register_noneatcraftitems ('masticone_fang',S('Masticone Fang'))
nssm:register_noneatcraftitems ('white_wolf_fur',S('White Wolf Fur'))
nssm:register_noneatcraftitems ('stoneater_mandible',S('Stoneater Mandible'))
nssm:register_noneatcraftitems ('ant_mandible',S('Ant Mandible'))
nssm:register_noneatcraftitems ('wolf_fur',S('Wolf Fur'))
nssm:register_noneatcraftitems ('felucco_fur',S('Felucco Fur'))
nssm:register_noneatcraftitems ('felucco_horn',S('Felucco Horn'))
nssm:register_noneatcraftitems ('mantis_skin',S('Mantis Husk'))
nssm:register_noneatcraftitems ('sand_bloco_skin',S('Sand Bloco Hide'))
nssm:register_noneatcraftitems ('sandworm_skin',S('Sandworm Hide'))
nssm:register_noneatcraftitems ('sky_iron',S('Sky Iron'))
nssm:register_noneatcraftitems ('web_string',S('Cobweb String'))
nssm:register_noneatcraftitems ('dense_web_string',S('Dense Cobweb String'))
nssm:register_noneatcraftitems ('black_powder',S('Black Powder'))
nssm:register_noneatcraftitems ('morelentir_dust',S('Soarkly Dark Stone Dust'))
nssm:register_noneatcraftitems ('empty_evocation_bomb',S('Empty Summoning Bomb'))

nssm:register_noneatcraftitems ('greedy_soul_fragment',S('Greedy Soul Fragment'))
nssm:register_noneatcraftitems ('lustful_soul_fragment',S('Lustful Soul Fragment'))
nssm:register_noneatcraftitems ('wrathful_soul_fragment',S('Wrathful Soul Fragment'))
nssm:register_noneatcraftitems ('proud_soul_fragment',S('Proud Soul Fragment'))
nssm:register_noneatcraftitems ('slothful_soul_fragment',S('Slothful Soul Fragment'))
nssm:register_noneatcraftitems ('envious_soul_fragment',S('Envious Soul Fragment'))
nssm:register_noneatcraftitems ('gluttonous_soul_fragment',S('Gluttonous Soul Fragment'))
nssm:register_noneatcraftitems ('gluttonous_moranga',S('Gluttonous Moranga'))
nssm:register_noneatcraftitems ('envious_moranga',S('Envious Moranga'))
nssm:register_noneatcraftitems ('proud_moranga',S('Proud Moranga'))
nssm:register_noneatcraftitems ('slothful_moranga',S('Slothful Moranga'))
nssm:register_noneatcraftitems ('lustful_moranga',S('Lustful Moranga'))
nssm:register_noneatcraftitems ('wrathful_moranga',S('Wrathful Moranga'))
nssm:register_noneatcraftitems ('greedy_moranga',S('Greedy Moranga'))

-- Food

nssm:register_eatcraftitems ('werewolf_leg',S('Werewolf Leg'),3)
nssm:register_eatcraftitems ('felucco_steak',S('Felucco Steak'),3)
nssm:register_eatcraftitems ('roasted_felucco_steak',S('Roasted Felucco Steak'),6)
nssm:register_eatcraftitems ('heron_leg',S('Moonheron Leg'),2)
nssm:register_eatcraftitems ('chichibios_heron_leg',S("Chichibio's Moonheron Leg"),4)
nssm:register_eatcraftitems ('crocodile_tail',S('Crocodile Tail'),3)
nssm:register_eatcraftitems ('roasted_crocodile_tail',S('Roasted Crocodile Tail'),6)
nssm:register_eatcraftitems ('roasted_werewolf_leg',S('Roasted_Werewolf Leg'),6)
nssm:register_eatcraftitems ('duck_legs',S('Duck Legs'),1)
nssm:register_eatcraftitems ('roasted_duck_legs',S('Roasted Duck Leg'),3)
nssm:register_eatcraftitems ('ant_leg',S('Ant Leg'),-1)
nssm:register_eatcraftitems ('roasted_ant_leg',S('Roasted Ant Leg'),4)
nssm:register_eatcraftitems ('spider_leg',S('Spider Leg'),-1)
nssm:register_eatcraftitems ('roasted_spider_leg',S('Roasted Spider Leg'),4)
nssm:register_eatcraftitems ('brain',S('Brain'),3)
nssm:register_eatcraftitems ('roasted_brain',S('Roasted Brain'),8)
nssm:register_eatcraftitems ('tentacle',S('Tentacle'),2)
nssm:register_eatcraftitems ('roasted_tentacle',S('Roasted Tentacle'),5)
nssm:register_eatcraftitems ('worm_flesh',S('Worm Meat'),-2)
nssm:register_eatcraftitems ('roasted_worm_flesh',S('Roasted Worm'),4)
nssm:register_eatcraftitems ('amphibian_heart',S('Amphibian Heart'),1)
nssm:register_eatcraftitems ('roasted_amphibian_heart',S('Roasted Amphibian Heart'),8)
nssm:register_eatcraftitems ('raw_scrausics_wing',S('Raw Scrausics Wing'),1)
nssm:register_eatcraftitems ('spicy_scrausics_wing',S('Spicy Scrausics Wing'),6)
nssm:register_eatcraftitems ('phoenix_nuggets',S('Phoenix Nuggets'),20)
nssm:register_eatcraftitems ('phoenix_tear',S('Phoenix Tear'),20)
nssm:register_eatcraftitems ('frosted_amphibian_heart',S('Frosted Amphibian Heart'),-1)
nssm:register_eatcraftitems ('surimi',S('Surimi'),4)
nssm:register_eatcraftitems ('amphibian_ribs',S('Amphibian Ribs'),2)
nssm:register_eatcraftitems ('roasted_amphibian_ribs',S('Roasted Amphibian Ribs'),6)
nssm:register_eatcraftitems ('dolidrosaurus_fin',S('Dolidrosaurus Fin'),-2)
nssm:register_eatcraftitems ('roasted_dolidrosaurus_fin',S('Roasted Dolidrosaurus Fin'),4)
nssm:register_eatcraftitems ('larva_meat',S('Larva Meat'),-1)
nssm:register_eatcraftitems ('larva_juice',S('Larva Juice'),-3)
nssm:register_eatcraftitems ('larva_soup',S('Larva Soup'),10)
nssm:register_eatcraftitems ('mantis_meat',S('Mantis Meat'),1)
nssm:register_eatcraftitems ('roasted_mantis_meat',S('Roasted Mantis'),4)
nssm:register_eatcraftitems ('spider_meat',S('Spider Meat'),-1)
nssm:register_eatcraftitems ('roasted_spider_meat',S('Roasted Spider'),3)
nssm:register_eatcraftitems ('silk_gland',S('Silk Gland'),-1)
nssm:register_eatcraftitems ('roasted_silk_gland',S('Roasted Silk Gland'),3)
nssm:register_eatcraftitems ('super_silk_gland',S('Super Silk Gland'),-8)
nssm:register_eatcraftitems ('roasted_super_silk_gland',S('Roasted Super Silk Gland'),2)

-- Cooking

nssm_register_recipe ('worm_flesh', 'roasted_worm_flesh', 12)
nssm_register_recipe ('duck_legs', 'roasted_duck_legs', 6)
nssm_register_recipe ('spider_leg', 'roasted_spider_leg', 6)
nssm_register_recipe ('felucco_steak', 'roasted_felucco_steak', 10)
nssm_register_recipe ('werewolf_leg', 'roasted_werewolf_leg', 10)
nssm_register_recipe ('brain', 'roasted_brain', 6)
nssm_register_recipe ('amphibian_heart', 'roasted_amphibian_heart', 6)
nssm_register_recipe ('tentacle', 'roasted_tentacle', 6)
nssm_register_recipe ('frosted_amphibian_heart', 'amphibian_heart', 8)
nssm_register_recipe ('heron_leg', 'chichibios_heron_leg', 20)
nssm_register_recipe ('raw_scrausics_wing', 'spicy_scrausics_wing', 12)
nssm_register_recipe ('ant_leg', 'roasted_ant_leg', 6)
nssm_register_recipe ('crocodile_tail', 'roasted_crocodile_tail', 16)
nssm_register_recipe ('dolidrosaurus_fin', 'roasted_dolidrosaurus_fin', 8)
nssm_register_recipe ('amphibian_ribs', 'roasted_amphibian_ribs', 12)
nssm_register_recipe ('mantis_meat', 'roasted_mantis_meat', 6)
nssm_register_recipe ('spider_meat', 'roasted_spider_meat', 6)
nssm_register_recipe ('silk_gland', 'roasted_silk_gland', 4)
nssm_register_recipe ('larva_juice', 'larva_soup', 20)
